### PR TITLE
enables global filesystem encryption support for efsbroker

### PR DESCRIPTION
**Pull request by x6j8x**
This PR enables the user to globally enforce the encryption of EFS filesystems. You can either simply enable encryption (and use the default EFS KMS Key) or pass a specific KMS KeyId.

### CODE REVIEW

**Comment by paulcwarren** [comment]
Hi @x6j8x,

Thanks for the PR.  Because encryption is an option on EFS's create filesystem wizard; i.e. per filesystem, we didn't like the fact that this new option was a command line input to the broker itself meaning that all filesystems would be created either with or without encryption with no chance for the developer to choose this for himself.  

The way we would normally expose this sort of feature is as a separate service or plans.  This allows the cf developer freedom of choice and  allows the cf operator to control access via the `enable-service-access` command.   

Given the implementation put forward we assumed your use case calls for encrypted filesystems always.  Even with the suggested modifications this would still be achievable by using the `enable-service-access` command to disable access to the unencrypted service/plans.

Let us know what you think
_Paul/Kai

**Comment by jmcarp** [comment]
@paulcwarren: this would be useful to us also. But I think we might want to flesh out the way we're configuring services and plans if we're going to configure encryption at that level. Right now, it looks like plans use hard-coded names to control performance mode. We *could* add an encrypted plan with an id like "encrypted", but what if we wanted a plan with both max io and encryption? I think it would make more sense to define a `Plan` type with fields for performance mode, encryption, kms key id, etc. We'd be happy to send a patch if that makes sense--what do you think?

**Comment by x6j8x** [comment]
@paulcwarren In my experience whether or not to apply encryption is not a developer, but an organisational choice. So at least in our environment enabling it (without choice) globally makes sense.

That said, we moved to our own broker implementation some time ago (the PR is pretty dated), so I go ahead an close this PR.

**Comment by jmcarp** [comment]
@x6j8x: is your implementation open source?

**Comment by x6j8x** [comment]
Unfortunately not!

**Comment by julian-hj** [comment]
@jmcarp we'd welcome a PR to set plans and/or services through configuration, if you are willing to create such a thing.

**Comment by jmcarp** [comment]
@julian-hj: sure, I can work on that PR when I have time. Meanwhile, it would be great to get a review on #4 so that I don't run into merge conflicts when I get around to this.

**Pull request closed without merging**
